상품 생성 API 구현
Yanabada/Yanabada_BE pull request #17
Opened 2024-01-05 12:59 UTC by Hwang-Kyu-Cheol

Resolves: #15 

## 개요
상품 생성 API 구현

## PR 유형
어떤 변경 사항이 있나요?
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

2024-01-05 13:06 UTC, tjdtn0219 commented on src/main/java/kr/co/fastcampus/yanabada/common/exception/AccessForbiddenException.java
> +        super(ErrorCode.ACCESS_FORBIDDEN.getMessage());
저희 enum 은 import static으로 빼는걸로 통일하는 건 어떠씬가요?

2024-01-05 13:06 UTC, tjdtn0219 commented on src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/Order.java
> +public class Order extends BaseEntity {
저희 클래스명 = 테이블명 으로 가기로 하지 않았나요?

2024-01-05 13:06 UTC, tjdtn0219 commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
>      private ProductStatus status;
Enum은
`@Enumerated(EnumType.String)` 붙여야 String 타입으로 DB에 저장됩니다!
위 어노테이션 붙이면 좋을 거 같습니다!

2024-01-05 13:17 UTC, deltawing71911 commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +public class ProductService {
로깅 추가하지 않아도 괜찮은 건가요?

2024-01-05 13:24 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/common/exception/AccessForbiddenException.java
> +        super(ErrorCode.ACCESS_FORBIDDEN.getMessage());
저는 좋은것 같습니다!!! 이 부분 다른 Exception들까지 수정해놓겠습니다

2024-01-05 13:26 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/Order.java
> +public class Order extends BaseEntity {
사실 그런 상황이 제일 베스트이긴 한데... 패키지 명, controller, service, repository 이름을 다 Order로 사용해서 이 부분도 이렇게 하면 객체를 Order로 생각하면 돼서 더 편할 것 같았습니다! 혹시 다른분들은 어떠신가요??

2024-01-05 13:27 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
>      private ProductStatus status;
성수님 저는 작성한거같은데 다시 한번만 확인해주실 수 있으신가요???

2024-01-05 13:27 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +public class ProductService {
지금 당장 로깅을 하지 않아서 추가하지 않았습니다! 나중에 로깅할 때 추가해도 괜찮을 것 같습니다.

2024-01-06 05:19 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/yanabada/common/exception/MemberNotFoundException.java
> +import static kr.co.fastcampus.yanabada.common.response.ErrorCode.MEMBER_NOT_FOUND;
그냥 임포트와 static 임포트의 차이점이 급 궁금하네요 ㅋㅋ jvm에서 힙의 데이터영역에서 정적메소드부분에 한번 만 올라가고, 그 후에 익셉션 객체 생성될 때 그 static 메소드를 재탕해서 써서 이렇게 바꾸신건가요?
개인적인 궁금증으로 물어본 것입니다!!!!!

2024-01-06 05:21 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/Order.java
> +public class Order extends BaseEntity {
카카오톡에서 규철님이 RoomOrder를 Order로 갑자기 바꿔도 되냐고 양해를 구하셨고 , 저랑 수지님은 동의 했습니다. 카카오톡에서 roomorder 검색 한번 해보세요. @tjdtn0219

2024-01-06 05:25 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
>      private ProductStatus status;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 성수님 그 파랑색 화살표 누르면 간소화 된 내용 표시 됩니다. 지금은 생략돼서 안보이셔서 그런거 같네요 ㅋㅋㅋㅋㅋ

2024-01-06 05:31 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
규철님 저희 예외 객체 빼곤 퍼블릭한 메소드에선 new 해서  객체 생성 안하기로 했습니다. 그래서 Response dto에서 빌더 어노테이션 추가하고 static 메소드로 만들어서 서비스 단에서 호출하여 사용하는 방법이 좋을 것 같습니다.
`public static AccommodationSummaryResponse from(
        Accommodation accommodation, boolean isSoldOut
    ) {
        return AccommodationSummaryResponse.builder()
            .id(accommodation.getId())
            .name(accommodation.getName())
            .address(accommodation.getAddress())
            .region(accommodation.getRegion())
            .category(accommodation.getCategory())
            .lowestPrice(accommodation.getLowestPrice())
            .image(accommodation.getImage())
            .soldOut(isSoldOut)
            .accommodationOption(
                AccommodationOptionResponse.from(accommodation.getAccommodationOption())
            )
            .build();
    }`
이렇게 DTO 에서 팩토리 패턴으로 생선 메소드 만들고
서비스에서  반환할때
`return AccommodationSummaryResponse.from(
            accommodation, isSoldOut(accommodation, startDate, endDate)
        );`
이렇게 return 하면 좋을 것 같습니다

2024-01-06 05:31 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
띠용....왜 깨지지....ㅜㅜ

2024-01-06 05:37 UTC, Programmer-may requested changes
이야기 나눠볼 것 적어 봤습니다! 수정 사항 반영되면 approve 하겠습니다

2024-01-06 23:05 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/common/exception/MemberNotFoundException.java
> +import static kr.co.fastcampus.yanabada.common.response.ErrorCode.MEMBER_NOT_FOUND;
제가 알기로 단지 가독성 때문으로 알고있습니다! 성능적인 부분에서는 똑같은 것으로 알고있습니다!

2024-01-06 23:19 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
넵! Response 부분 빌더패턴 추가해서 바꿔놓겠습니다

2024-01-07 00:03 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
주현님 그런데 이 부분 관련해서 논의가 필요해보입니다.
일단 주현님이 올려주신 코드는 생성자, 빌더, 팩토리 메소드로 모두 생성이 가능합니다. 그래서 실제 객체 생성을 팩토리 메소드로 제한하기 위해서는 record를 class type으로 변경해야 합니다. record는 AllArgsConstructor를 기본으로 생성해주기 때문에, new 생성은 불가피합니다. 따라서, class로 변경하고 생성자를 private으로 바꾼후 팩토리 메소드를 만듭니다(Entity 처럼). Builder는 필요가 없어보입니다. 왜냐하면 Builder를 추가할 경우 실제 객체를 생성하려는 사용자는 빌더로도 생성할 수 있고 팩토리로도 생성할 수 있기 때문입니다.
저는 사실 Dto가 생성될 때 new나 팩토리 메소드로 생성되는 것이 크게 상관 없다고 생각합니다. 왜냐하면 어떻게 생성되어도 실제 데이터는 변하지 않기 때문입니다. 중요한 것은 사용자가 편하도록 매개변수로 Product를 받아서 ProductIdResponse를 반환해주는 메소드가 있는지라고 생각합니다. 
이 부분은 저희끼리 얘기를 해 볼 필요가 있을 것 같아요! 월욜날에 바로 하시죠!!!

2024-01-07 05:31 UTC, tjdtn0219 approved these changes

2024-01-07 05:31 UTC, tjdtn0219 commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
>      private ProductStatus status;
확인해씀다ㅋㅋ

2024-01-07 05:35 UTC, deltawing71911 approved these changes

2024-01-07 05:46 UTC, deltawing71911 commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
검증 로직들을 유틸리티 클래스로 분리하는게 좋지 않나요? 재사용할 일이 있을 것 같은 생각이 들었습니다.

2024-01-07 09:40 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
네 확인하였습니다 ! 월욜 스크럼때 의논해보죠!

2024-01-08 01:27 UTC, tjdtn0219 approved these changes

2024-01-08 01:38 UTC, Hwang-Kyu-Cheol commented on src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
> +    }
지금 제 생각에는 재사용할 일이 없다고 생각해서 따로 안빼놨는데, 만약에 구현하다가 재사용할 일이 생기면 유틸클래스로 분리하겠습니다!

2024-01-08 01:50 UTC, Programmer-may approved these changes
고생하셨습니다!!!

2024-01-08 01:52 UTC, merged